version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/app
    command: bundle exec hanami server --host 0.0.0.0
    ports:
      - 2300:2300
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./client:/client
      - ./public:/public
    ports:
      - 3000:3000
  
